default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: 
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: original_app_development

test:
  <<: *default
  database: original_app_test

production:
  <<: *default
  database: original_app_production